name: shopping_app_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  device_preview: ^1.2.0
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.1
  shimmer_animation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
